---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Run 'docker compose version'.
    ansible.builtin.command: docker compose version
    register: docker_compose_version
    changed_when: false

  - name: Check if docker compose is installed.
    ansible.builtin.assert:
      that: "'is not a docker command' not in docker_compose_version.stdout"
      fail_msg: "Docker Compose is not installed."
      success_msg: "Docker Compose is installed."
